version: "3.8"

services:
  ollama:
    # image: ollama/ollama:0.1.16
    build:
      context: .
      dockerfile: app-ollama.Dockerfile
    ports:
      - "11434:11434"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped
